#pragma config(Motor,  port2,           DFR,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           DBL,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           DBR,           tmotorVex393, openLoop)
#pragma config(Motor,  port9,           DFL,           tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		motor[DFR] = vexRT[Ch2];
		motor[DBR] = vexRT[Ch2];
		motor[DFL] = vexRT[Ch3];
		motor[DBL] = vexRT[Ch3];
	}

}
