#pragma config(Motor,  port2,           rLift1,        tmotorVex393, openLoop)
#pragma config(Motor,  port3,           rLift2,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           rLift3,        tmotorVex393, openLoop)
#pragma config(Motor,  port5,           lLift1,        tmotorVex393, openLoop)
#pragma config(Motor,  port6,           lLift2,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           lLift3,        tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//function for right lift
void rightLift(int a)//3 and 5 reverse!!!
{
	motor[rLift1] = a;
	motor[rLift2] = a;
	motor[rLift3] = a;
}
//function for left lift
void leftLift (int a)
{
	motor[lLift1] = a;
	motor[lLift2] = a;
	motor[lLift3] = a;
}
//function for lift
void lift(int a)
{
	rightLift(a);
	leftLift(a);
}


task main()//lift control
{
	while(true)
	{
		if ((vexRT[Btn6U]==1)&&(vexRT[Btn6D]==0))
		{
			lift(127);
		}
		else if ((vexRT[Btn6D]==1)&&(vexRT[Btn6U]==0))
		{
			lift(-127);
		}
		else
		{
			lift(0);
		}
	}
}
