#pragma config(Sensor, dgtl1,  limit1,         sensorTouch)
#pragma config(Sensor, dgtl2,  liftLimit,      sensorTouch)
#pragma config(Sensor, dgtl3,  liftLimit1,     sensorTouch)
#pragma config(Sensor, dgtl7,  solenoid,       sensorDigitalOut)
#pragma config(Motor,  port1,           rLift3,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port2,           DFR,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           DBR,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           lLift2,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           lLift1,        tmotorVex393, openLoop)
#pragma config(Motor,  port6,           rLift1,        tmotorVex393, openLoop)
#pragma config(Motor,  port7,           lLift3,        tmotorVex393, openLoop)
#pragma config(Motor,  port8,           DFL,           tmotorVex393, openLoop)
#pragma config(Motor,  port9,           rLift2,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          DBL,           tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int MIN_JOYSTICK_ACTIVATION_THRESHOLD = 10;//tank drive threshold
const int error = 10;//define the error

int valveUseCount = 0;
float valveUseMultiplier = 0.2;
long valveOpenTime = 40;

long timeSetToOpen = 0;
bool pneumaticButtonDown = false;

void gyroTurn(int degrees10)  //specify the amount of degrees to turn
{
	while((abs(SensorValue[in8]) < degrees10 + error) || (abs(SensorValue[in8]) < degrees10 - error))
	{
		motor[port1] = 63;
		motor[port2] = -63;
	}

	motor[port1] = -5;  //brake/return to original
	motor[port2] = 5;
	wait1Msec(250);
	motor[port1] = 0;
	motor[port2] = 0;
}
void driveStraight1(int a)
{
	motor[DFR] = a;
	motor[DBR] = a;
	motor[DFL] = a;
	motor[DBL] = a;
}
void driveStraight(float dist, int speed)
{
	while((SensorValue(dgtl1) < 360 * dist / (4 * PI) + error) || (SensorValue(dgtl1) < 360 * dist / (4 * PI) + error))
	motor[DFR] = speed;
	motor[DBR] = speed;
	motor[DFL] = speed;
	motor[DBL] = speed;

}

void driveRight(int a)
{
	motor[DFR] = a;
	motor[DBR] = a;
}

void driveLeft(int a)
{
	motor[DFL] = a;
	motor[DBL] = a;
}

void turn(int a)
{
	driveRight(-a);
	driveLeft(a);
}

//function for right lift
void rightLift(int a)//3 and 5 reverse!!!
{
	motor[rLift1] = a;
	motor[rLift2] = a;
	motor[rLift3] = a;
}
//function for left lift
void leftLift (int a)
{
	motor[lLift1] = a;
	motor[lLift2] = a;
	motor[lLift3] = a;
}
//function for lift
void lift(int a)
{
	rightLift(a);
	leftLift(a);
}

task autonomous()
{
	SensorType[in8] = sensorNone;
	wait1Msec(1000);
	//Reconfigure Analog Port 8 as a Gyro sensor and allow time for ROBOTC to calibrate it
	SensorType[in8] = sensorGyro;
	wait1Msec(2000);

	if(SensorValue(limit1) == 0) //hang a cube from the back, move backwards until the limit switch is pressed
	{
		driveStraight1(-100);
	}
	else if(SensorValue(limit1) == 1)
	{
		wait1Msec(1000); //wait for the cube to release from the robot
		driveStraight1(100);
	}

	//	gyroTurn(45);//turns 45 degrees

	turn(100);
	wait1Msec(1000);
	turn(0);

	driveStraight(sqrt(2), 50);//returns to starting position
	driveStraight(1.5, 50);
	//do something with intake
	if(SensorValue(limit1) == 0)
	{
		driveStraight1(-100);
	}
}

task main()
{
	while(1 == 1)
	{
		//get current time

		int valveUseCount = 0; //number of times button pressed/activated
		float valveUseMultiplier = 0.2; // constant that changes amt of time valve opened
		long valveOpenTime = 50; //initial amt of time opened

		long timeSetToOpen = 0;
		bool pneumaticButtonDown = false;
		long currentTime = nSysTime;



		if((vexRT[Btn5U] == 1) && !pneumaticButtonDown)           // If button 6U (upper right shoulder button) is pressed:
		{
			pneumaticButtonDown = true;
			SensorValue[solenoid] = 1;
			timeSetToOpen = currentTime + valveOpenTime; //timeSetToOpen is time it should be open
			timeSetToOpen += (long)(valveUseMultiplier * valveUseCount * 40);
			valveUseCount++;
		}

		if(currentTime > timeSetToOpen)
		{
			SensorValue[solenoid] = 0; //solenoid is the pneumatic sensor
		}

		if((vexRT[Btn5U] == 0) && pneumaticButtonDown)
		{
			pneumaticButtonDown = false;
		}

		if ((vexRT[Btn6U]==1)&&(vexRT[Btn6D]==0))
		{
			lift(50);
		}

		else if ((vexRT[Btn6D]==1)&&(vexRT[Btn6U]==0))
		{
			//make a limit switch such that the intake when putting in the skyrise can only go down so far.
			//

			if(SensorValue(liftLimit) == 0)
			{
				lift(-50);
			}
			else if(SensorValue(liftLimit) == 1)
			{
				lift(0);
			}
		}

		else
		{
			lift(0);
		}

		//tank drive


		motor[DFL] = vexRT[Ch3];
		motor[DBL] = vexRT[Ch3];
		motor[DFR] = vexRT[Ch2];
		motor[DBR] = vexRT[Ch2];
	}



}


//touch2 refers to a lift limit
//touch1 refers to the back of the robot's touch sensor
