#pragma config(Sensor, dgtl1,  limit1,         sensorTouch)
#pragma config(Sensor, dgtl2,  limit2,         sensorTouch)
#pragma config(Motor,  port1,           DFL,           tmotorVex393, openLoop)
#pragma config(Motor,  port2,           DFR,           tmotorVex393, openLoop)
#pragma config(Motor,  port3,           DBR,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           DBL,           tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int error = 10;	//define the error

void gyroTurn(int degrees10)	//specify the amount of degrees to turn
{
	while((abs(SensorValue[in8]) < degrees10 + error) || (abs(SensorValue[in8]) < degrees10 - error))
	{
		motor[port1] = 63;
		motor[port2] = -63;
	}

	motor[port1] = -5;//brake/return to original
	motor[port2] = 5;
	wait1Msec(250);
	motor[port1] = 0;
	motor[port2] = 0;
}

void drive_straight(float dist, int speed)
{
	while((SensorValue(dgtl1) < 360 * dist / (4 * PI) + error) || (SensorValue(dgtl1) < 360 * dist / (4 * PI) + error))
		motor[port1] = speed;

}

task autonomous()
{
	SensorType[in8] = sensorNone;
	wait1Msec(1000);
	//Reconfigure Analog Port 8 as a Gyro sensor and allow time for ROBOTC to calibrate it
	SensorType[in8] = sensorGyro;
	wait1Msec(2000);

	if(SensorValue(limit1) == 0) //hang a cube from the back, move backwards until the limit switch is pressed
	{
		motor[port1] = -100;
		motor[port2] = -100;
	}
	else if(SensorValue(limit1) == 1)
	{
		wait1Msec(1000); //wait for the cube to release from the robot
		motor[port1] = 100;
		motor[port2] = 100;
	}

	gyroTurn(45);//turns 45 degrees

	drive_straight(sqrt(2), 50);//returns to starting position
	drive_straight(1.5, 50);
	//do something with intake
	if(SensorValue(limit1) == 0)
	{
		motor[port1] = -100;
		motor[port2] = -100;

	}
}

task main()
{
	int X2 = 0, Y1 = 0, X1 = 0, threshold = 15;

	//Loop Forever
	while(1 == 1)
	{
		//Create "deadzone" for Y1/Ch3
		if(abs(vexRT[Ch3]) > threshold)
			Y1 = vexRT[Ch3];
		else
			Y1 = 0;
		//Create "deadzone" for X1/Ch4
		if(abs(vexRT[Ch4]) > threshold)
			X1 = vexRT[Ch4];
		else
			X1 = 0;
		//Create "deadzone" for X2/Ch1
		if(abs(vexRT[Ch1]) > threshold)
			X2 = vexRT[Ch1];
		else
			X2 = 0;

		//Remote Control Commands
		motor[DFR] = Y1 - X2 - X1;
		motor[DBR] =  Y1 - X2 + X1;
		motor[DFL] = Y1 + X2 + X1;
		motor[DBL] =  Y1 + X2 - X1;
	}
}

//touch2 refers to a lift limit
//t ouch1 refers to the back of the robot's touch sensor
