#pragma config(Motor,  port1,           holo,          tmotorVex393, openLoop)
#pragma config(Motor,  port2,           DFL,           tmotorVex393, openLoop)
#pragma config(Motor,  port3,           DFR,           tmotorVex393, openLoop)
#pragma config(Motor,  port4,           DBL,           tmotorVex393, openLoop)
#pragma config(Motor,  port5,           DBR,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           rightIntake,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           leftIntake,    tmotorVex393, openLoop)
#pragma config(Motor,  port8,           leftArm,       tmotorVex393, openLoop)
#pragma config(Motor,  port9,           rightArm,      tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int tol = 20;
int straight;
int ptturn;
int side;


void driveLeft (int pwr)
{
	motor[DBL] = pwr;
	motor[DFL] = pwr;
}

void driveRight (int pwr)
{
	motor[DFR] = pwr;
	motor[DBR] = pwr;
}

void driveStraight (int pwr)
{
	driveRight(pwr);
	driveLeft(pwr);
}

void turnRight (int pwr)
{
	driveRight(-pwr);
	driveLeft (pwr);
}

void turnLeft (int pwr)
{
	driveRight(pwr);
	driveLeft(-pwr);
}

task main()
{

	while (true)
	{
		if(abs(vexRT[Ch2]) > tol)//set straight
			straight = vexRT[Ch2];
		else
			straight = 0;
		if(abs(vexRT[Ch4]) > tol) //set ptturn
			ptturn = vexRT[Ch4];
		else
			ptturn = 0;
		if(abs(vexRT[Ch1]) > tol) //set side
			side = vexRT[Ch1];
		else
			side = 0;
		if((abs(-ptturn + straight)<=127) && (abs(ptturn + straight)<=127))
		{
			driveRight(-ptturn/2 + straight*2/3);
			driveLeft(ptturn/2 + straight*2/3);

			motor[holo]= side;
		}
		else if(abs(-ptturn + straight) > 127)//(pttrn + straight)
		{
			driveRight(100);
			driveLeft(-100);
			motor[holo]= side;
		}
		else if(abs(-ptturn + straight) > 127)
		{

			driveRight(-100);
			driveLeft(100);
			motor[holo]= side;
		}
		else
		{
			driveLeft(0);
			driveRight(0);
			motor[holo]=0;
		}

		//intake
		if((vexRT[Btn5U] == 1) && (vexRT[Btn5D] == 0))
		{
			motor[rightIntake] = 100;
			motor[leftIntake] = 100;
		}
		else if((vexRT[Btn5D] == 1) && (vexRT[Btn5U] == 0))
		{
			motor[rightIntake] = -100;
			motor[leftIntake] = -100;

		}
		else
		{
			motor[rightIntake] = 0;
			motor[leftIntake] = 0;
		}

		//arm
		if((vexRT[Btn6U] == 1) && (vexRT[Btn6D] == 0))
		{
			motor[rightArm] = 100;
			motor[leftArm] = 100;
		}
		else if((vexRT[Btn6D] == 1) && (vexRT[Btn6U] == 0))
		{
			motor[rightArm] = -100;
			motor[leftArm] = -100;
		}
		else
		{
			motor[rightArm] = 0;
			motor[leftArm] = 0;
		}
	}
}
