#pragma config(Motor,  port1,           rightArm,      tmotorVex393, openLoop)
#pragma config(Motor,  port2,           leftArm,       tmotorVex393, openLoop)
#pragma config(Motor,  port3,           rightIntake,   tmotorVex393, openLoop)
#pragma config(Motor,  port4,           leftIntake,    tmotorVex393, openLoop)
#pragma config(Motor,  port5,           DFR,           tmotorVex393, openLoop)
#pragma config(Motor,  port6,           DBR,           tmotorVex393, openLoop)
#pragma config(Motor,  port7,           DFL,           tmotorVex393, openLoop)
#pragma config(Motor,  port8,           DBL,           tmotorVex393, openLoop)
#pragma config(Motor,  port9,           holo,          tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

const int MIN_JOYSTICK_ACTIVATION_THRESHOLD = 10;
int straight;
int ptturn;
int side;

task drive();

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	// .....................................................................................
	// Insert user code here.
	// .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

void driveRight(int a)
{
	motor[DFR]=a;
	motor[DBR]=a;
}

void driveLeft(int a)
{
	motor[DFL]=a;
	motor[DBL]=a;
}

void turnRight(int a)
{
	driveRight(-a);
	driveLeft(a);
}

void turnLeft(int a)
{
	driveRight(a);
	driveLeft(-a);
}

//intake
if((vexRT[Btn5U] == 1) && (vexRT[Btn5D] == 0))
{
	motor[rightIntake] = 100;
	motor[leftIntake] = 100;
}
else if((vexRT[Btn5D] == 1) && (vexRT[Btn5U] == 0))
{
	motor[rightIntake] = -100;
	motor[leftIntake] = -100;
}
else
{
	motor[rightIntake] = 0;
	motor[leftIntake] = 0;
}

//arm
if((vexRT[Btn6U] == 1) && (vexRT[Btn6D] == 0))
{
	motor[rightArm] = 100;
	motor[leftArm] = 100;
}
else if((vexRT[Btn6D] == 1) && (vexRT[Btn6U] == 0))
{
	motor[rightArm] = -100;
	motor[leftArm] = -100;
}
else
{
	motor[rightArm] = 0;
	motor[leftArm] = 0;
}


task drive()
{
	while (true)
	{
		if(abs(vexRT[Ch2]) > MIN_JOYSTICK_ACTIVATION_THRESHOLD)//set straight
		{
			straight = vexRT[Ch2];
		}
		else
		{
			straight = 0;
		}
		if(abs(vexRT[Ch4]) > MIN_JOYSTICK_ACTIVATION_THRESHOLD) //set ptturn
		{
			ptturn = vexRT[Ch4];
		}
		else
		{
			ptturn = 0;
		}
		if(abs(vexRT[Ch1]) > MIN_JOYSTICK_ACTIVATION_THRESHOLD) //set side
		{
			side = vexRT[Ch1];
		}
		else
		{
			side = 0;
		}
		if((abs(-ptturn + straight)<=127) && (abs(ptturn + straight)<=127))
		{
			driveRight(-ptturn/2 + straight*2/3);
			driveLeft(ptturn/2 + straight*2/3);
			motor[holo] = side;
		}
		else if(abs(-ptturn + straight) > 127)//(pttrn + straight)
		{
			driveRight(100);
			driveLeft(-100);
			motor[holo] = side;
		}
		else if(abs(-ptturn + straight) > 127)
		{
			driveRight(-100);
			driveLeft(100);
			motor[holo] = side;
		}
		else
		{
			driveLeft(0);
			driveRight(0);
			motor[holo]=0;
		}
	}
}

	task usercontrol()
	{
		// User control code here, inside the loop

		while (true)
		{
			// This is the main execution loop for the user control program. Each time through the loop
			// your program should update motor + servo values based on feedback from the joysticks.

			// .....................................................................................
			// Insert user code here. This is where you use the joystick values to update your motors, etc.
			// .....................................................................................

			UserControlCodePlaceholderForTesting(); // Remove this function call once you have "real" code.
		}
	}
