#pragma config(Motor,  port1,           rightArm,      tmotorVex393, openLoop)
#pragma config(Motor,  port2,           leftArm,       tmotorVex393, openLoop)
#pragma config(Motor,  port3,           rightIntake,   tmotorVex393, openLoop)
#pragma config(Motor,  port4,           DFL,           tmotorVex393, openLoop)
#pragma config(Motor,  port5,           DFR,           tmotorVex393, openLoop)
#pragma config(Motor,  port6,           middle,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           DBR,           tmotorVex393, openLoop)
#pragma config(Motor,  port8,           DBL,           tmotorVex393, openLoop)
#pragma config(Motor,  port9,           leftIntake,    tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

	#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

const int MIN_JOYSTICK_ACTIVATION_THRESHOLD = 2;

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	// .....................................................................................
	// Insert user code here.
	// .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

void driveRight(int a)
{
	motor[DFR]=a;
	motor[DBR]=a;
}

void driveLeft(int a)
{
	motor[DFL]=a;
	motor[DBL]=a;
}

void turnRight(int a)
{
	driveRight(-a);
	driveLeft(a);
}

void turnLeft(int a)
{
	driveRight(a);
	driveLeft(-a);
}


	task usercontrol()
	{
		// User control code here, inside the loop

		while (true)
		{
			motor[DFR]=vexRT[Ch2];
			motor[DBR]=vexRT[Ch2];
			motor[DFL]=vexRT[Ch2];
			motor[DBL]=vexRT[Ch2];
			motor[middle]=vexRT[Ch1];

			if(abs(vexRT[Ch4]) > MIN_JOYSTICK_ACTIVATION_THRESHOLD)
			{
				turnRight(127);
			}
			else
			{
				turnRight(0);
			}
				if(abs(vexRT[Ch3]) > tol)//set straight
			straight = vexRT[Ch3];
		else
			straight = 0;
		if(abs(vexRT[Ch1]) > tol) //set ptturn
			ptturn = vexRT[Ch1];
		else
			ptturn = 0;
		if(abs(vexRT[Ch4]) > tol) //set side
			side = vexRT[Ch4];
		else
			side = 0;
		if((abs(-ptturn + straight)<=127) && (abs(ptturn + straight)<=127))
		{
			driveRight(-ptturn/2 + straight*2/3);
			driveLeft(ptturn/2 + straight*2/3);
			motor[holo]= side;
		}
		else if(abs(-ptturn + straight) > 127)//(pttrn + straight)
		{
			driveRight(100);
			driveLeft(-100);
			motor[holo]= side;
		}
		else if(abs(-ptturn + straight) > 127)
		{
			driveRight(-100);
			driveLeft(100);
			motor[holo]= side;
		}
		}
	}
