#pragma config(Motor,  port2,           DFR,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           DFL,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           DBR,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           DBL,           tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		motor[port2] = vexRT[Ch3];

		motor[port3] = vexRT[Ch2];

		motor[port4] = vexRT[Ch3];

		motor[port5] = vexRT[Ch2];
	}

	int number = 0;

	if
}
