#pragma config(Motor,  port2,           rLift1,        tmotorVex393, openLoop)
#pragma config(Motor,  port3,           rLift2,        tmotorVex393, openLoop)
#pragma config(Motor,  port4,           lLift1,        tmotorVex393, openLoop)
#pragma config(Motor,  port5,           lLift2,        tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



const int GROUND = a; //5D
const int SKRISE_DISPENSER = b; //8L
const int LOW_GOAL = c; //8D
const int MID_GOAL = d; //8R
const int HIGH_GOAL = e; //8U
const int MAX_HEIGHT = f; //5U


//function for right lift
void rightLift(int a)
{
	motor[rLift1] = a;
	motor[rLift2] = a;
}
//function for left lift
void leftLift (int a)
{
	motor[lLift1] = a;
	motor[lLift2] = a;
}

//function for lift
void lift(int a)
{
	rightLift(a);
	leftLift(a);
}


//move lift until desired value is reached
void moveLift(int a)
{
	if(SensorValue(rlift1) < a)
	{
		lift(127);
	}
	else if(SensorValue(rlift1) > a)
	{
		lift(-127);
	}
	else
	{
		lift(0);
	}
}


task presets()
{
	nMotorEncoder[rlift1] = 0;

	bool preset = false; //initially preset is false to allow for manual control


	if((vexRT[Btn8UXmtr2] == 1) || (vexRT[Btn8DXmtr2] == 1) || (vexRT[Btn8LXmtr2] == 1)
		|| (vexRT[Btn8RXmtr2] == 1)|| (vexRT[Btn5UXmtr2] == 1) || (vexRT[Btn5DXmtr2] == 1)
	&& (vexRT[Btn6UXmtr2] == 0) && (vexRT[Btn6DXmtr2] == 0))
	{
		preset = true; //enabling the auto control
	}
	else if((vexRT[Btn8UXmtr2] == 0) && (vexRT[Btn8DXmtr2] == 0) && (vexRT[Btn8LXmtr2] == 0)
		&& (vexRT[Btn8RXmtr2] == 0)&& (vexRT[Btn5UXmtr2] == 0) && (vexRT[Btn5DXmtr2] == 0)
	|| (vexRT[Btn6UXmtr2] == 1) || (vexRT[Btn6DXmtr2] == 1))
	{
		preset = false;	//enabling manual control
	}

	if(preset == true)
	{
		if((vexRT[Btn8UXmtr2] == 0) && (vexRT[Btn8DXmtr2] == 1) && (vexRT[Btn8RXmtr2] == 0) && (vexRT[Btn8LXmtr2] == 0)
			&& (vexRT[Btn5UXmtr2] == 0) && (vexRT[Btn5DXmtr2] == 0))
		{
			moveLift(LOW_GOAL);//move lift until the value is reached
		}
		else if((vexRT[Btn8UXmtr2] == 0) && (vexRT[Btn8DXmtr2] == 0) && (vexRT[Btn8RXmtr2] == 1) && (vexRT[Btn8LXmtr2] == 0)
			&& (vexRT[Btn5UXmtr2] == 0) && (vexRT[Btn5DXmtr2] == 0))
		{
			moveLift(MID_GOAL);
		}
		else if((vexRT[Btn8UXmtr2] == 0) && (vexRT[Btn8DXmtr2] == 1) && (vexRT[Btn8RXmtr2] == 0) && (vexRT[Btn8LXmtr2] == 0)
			&& (vexRT[Btn5UXmtr2] == 0) && (vexRT[Btn5DXmtr2] == 0))
		{
			moveLift(HIGH_GOAL);
		}
		else if((vexRT[Btn8UXmtr2] == 0) && (vexRT[Btn8DXmtr2] == 0) && (vexRT[Btn8RXmtr2] == 0) && (vexRT[Btn8LXmtr2] == 0)
			&& (vexRT[Btn5UXmtr2] == 0) && (vexRT[Btn5DXmtr2] == 1))
		{
			moveLift(GROUND);
			nMotorEncoder[rlift1] = 0;
		}
		else if((vexRT[Btn8UXmtr2] == 0) && (vexRT[Btn8DXmtr2] == 0) && (vexRT[Btn8RXmtr2] == 0) && (vexRT[Btn8LXmtr2] == 0)
			&& (vexRT[Btn5UXmtr2] == 1) && (vexRT[Btn5DXmtr2] == 0))
		{
			moveLift(MAX_HEIGHT);
		}
		else if((vexRT[Btn8UXmtr2] == 0) && (vexRT[Btn8DXmtr2] == 0) && (vexRT[Btn8RXmtr2] == 0) && (vexRT[Btn8LXmtr2] == 1)
			&& (vexRT[Btn5UXmtr2] == 0) && (vexRT[Btn5DXmtr2] == 0))
		{
			moveLift(SKYRISE_DISPENSER);
		}
	}

	//manual control for lift
	else if(preset == false)
	{
		if((vexRT[Btn6UXmtr2] == 1) && (vexRT[Btn6DXmtr2] == 0))
		{
			lift(127);
		}
		else if((vexRT[Btn6DXmtr2] == 1) && (vexRT[Btn6UXmtr2] == 0))
		{
			lift(-127);
		}
		else
		{
			lift(0);
		}
	}
}


task usercontrol()
{
	// User control code here, inside the loop
	while(true)
	{
		startTask(presets);
	}
}
