#pragma config(Motor,  port1,           rLift1,        tmotorVex393, openLoop)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           backLeft,      tmotorVex393, openLoop)
#pragma config(Motor,  port4,           rLift3,        tmotorVex393, openLoop)
#pragma config(Motor,  port5,           lLift1,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           lLift2,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           lLift3,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           backRight,     tmotorVex393, openLoop)
#pragma config(Motor,  port9,           frontLeft,     tmotorVex393, openLoop)
#pragma config(Motor,  port10,          rLift2,        tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//6 motor lift
//mecanum drive

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!


/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

void rightLift(int a)
{
	motor[rLift1] = a;
	motor[rLift2] = a;
	motor[rLift3]= a;
}

void leftLift(int a)
{
	motor[lLift1] = a;
	motor[lLift2] = a;
	motor[lLift3]= a;
}


task usercontrol()
{
	//Create "deadzone" variables. Adjust threshold vusercontrolrease/decrease deadzone
	int X2 = 0, Y1 = 0, X1 = 0, threshold = 15;

	//Loop Forever
	while(1 == 1)
	{
		//Create "deadzone" for Y1/Ch3
		if(abs(vexRT[Ch3]) > threshold)
			Y1 = vexRT[Ch3];
		else
			Y1 = 0;
		//Create "deadzone" for X1/Ch4
		if(abs(vexRT[Ch4]) > threshold)
			X1 = vexRT[Ch4];
		else
			X1 = 0;
		//Create "deadzone" for X2/Ch1
		if(abs(vexRT[Ch1]) > threshold)
			X2 = vexRT[Ch1];
		else
			X2 = 0;

		//Remote Control Commands
		motor[frontRight] = Y1 - X2 + X1;
		motor[backRight] =  Y1 - X2 - X1;
		motor[frontLeft] = Y1 + X2 - X1;
		motor[backLeft] =  Y1 + X2 + X1;
	}
	//6 motor lift control
	if((vexRT[Btn5U] == 1) && (vexRT[Btn5D] == 0))
	{
		rightLift(100);
		leftLift(100);
	}
	else if((vexRT[Btn5D] == 1) && (vexRT[Btn5U] == 0))
	{
		rightLift(-100);
		leftLift(-100);
	}
	else
	{
		rightLift(0);
		leftLift(0);
	}
}
