#pragma config(Motor,  port1,           rLift1,        tmotorVex393, openLoop)
#pragma config(Motor,  port2,           DFR,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           DBL,           tmotorVex393, openLoop)
#pragma config(Motor,  port4,           rLift3,        tmotorVex393, openLoop)
#pragma config(Motor,  port5,           lLift1,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           lLift2,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           lLift3,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           DBR,           tmotorVex393, openLoop)
#pragma config(Motor,  port9,           DFL,           tmotorVex393, openLoop)
#pragma config(Motor,  port10,          rLift2,        tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//6 motor lift
//tank drive

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!


/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

void driveRight(int a)
{
	motor[DFR]=a;
	motor[DBR]=a;
}

void driveLeft(int a)
{
	motor[DFL]=a;
	motor[DBL]=a;
}

void turnRight(int a)
{
	driveRight(-a);
	driveLeft(a);
}

task usercontrol()
{
	motor[DFR]=vexRT[Ch3];
	motor[DBR]=vexRT[Ch3];
	motor[DFL]=vexRT[Ch2];
	motor[DBL]=vexRT[Ch2];
}


void rightLift(int a)
{
	motor[rLift1] = a;
	motor[rLift2] = a;
	motor[rLift3]= a;
}

void leftLift(int a)
{
	motor[lLift1] = a;
	motor[lLift2] = a;
	motor[lLift3]= a;
}


//6 motor lift control
if((vexRT[Btn5U] == 1) && (vexRT[Btn5D] == 0))
{
	rightLift(100);
	leftLift(100);
}
else if((vexRT[Btn5D] == 1) && (vexRT[Btn5U] == 0))
{
	rightLift(-100);
	leftLift(-100);
}
else
{
	rightLift(0);
	leftLift(0);
}
