#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in8,    gyro1,          sensorGyro)
#pragma config(Sensor, dgtl1,  limit1,         sensorTouch)
#pragma config(Sensor, dgtl2,  limit2,         sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           DFR,           tmotorVex393, openLoop, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port3,           DBR,           tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_3, 1000)
#pragma config(Motor,  port4,           DFL,           tmotorVex393, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port5,           DBL,           tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_4, 1000)
#pragma config(Motor,  port6,           rLift1,        tmotorVex393, openLoop)
#pragma config(Motor,  port7,           rLift2,        tmotorVex393, openLoop)
#pragma config(Motor,  port8,           lLift1,        tmotorVex393, openLoop)
#pragma config(Motor,  port9,           lLift2,        tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

const int error = 30;	//define the error


const int GROUND = 0; //5D
const int SKYRISE_DISPENSER = 0; //8L
const int LOW_GOAL = 0; //8D
const int MID_GOAL = 0; //8R
const int HIGH_GOAL = 0; //8U
const int MAX_HEIGHT = 0; //5U

int button5D = vexRT[Btn5DXmtr2];
int button8L = vexRT[Btn8LXmtr2];
int button8D = vexRT[Btn8DXmtr2];
int button8R = vexRT[Btn8RXmtr2];
int button8U = vexRT[Btn8UXmtr2];
int button5U = vexRT[Btn5UXmtr2];


///////////////////////Drive///////////////////////

void driveLeft(int a)
{
	motor[DBL] = a;
	motor[DFL] = a;
}

void driveRight(int a)
{
	motor[DBR] = a;
	motor[DFR] = a;
}

void drive_straight(float dist, int speed)
{
	while((nMotorEncoder[DBR] < 360 * dist / (4 * PI) + error) || (nMotorEncoder[DBR] < 360 * dist / (4 * PI) - error))
	{
		driveRight(speed);
		driveLeft(speed);
	}
}

///////////////////////Lift///////////////////////

//function for right lift
void rightLift(int a)
{
	motor[rLift1] = a;
	motor[rLift2] = a;
}
//function for left lift
void leftLift (int a)
{
	motor[lLift1] = a;
	motor[lLift2] = a;
}

//function for lift
void lift(int a)
{
	rightLift(a);
	leftLift(a);
}


//move lift until desired value is reached
void moveLift(int a)
{
	if(nMotorEncoder[rLift1] < a)
	{
		lift(127);
	}
	else if(nMotorEncoder[rLift1] > a)
	{
		lift(-127);
	}
	else
	{
		lift(0);
	}
}

///////////////////////Gyro///////////////////////

void gyroTurn(int degrees10)  //specify the amount of degrees to turn
{
	while((abs(SensorValue[in8]) < degrees10))
	{
		motor[port1] = 63;
		motor[port2] = -63;
	}
}


void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}


task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

//////////////////////////////////////////////////

void presets(bool * const preset)
{
	nMotorEncoder[rLift1] = 0;

	if((vexRT[Btn8UXmtr2]== 1) || (vexRT[Btn8DXmtr2]== 1) || (vexRT[Btn8LXmtr2] == 1)|| (vexRT[Btn8RXmtr2]== 1)
		|| (vexRT[Btn5UXmtr2] == 1) || (vexRT[Btn5DXmtr2] == 1)&& (vexRT[Btn6UXmtr2] == 0) && (vexRT[Btn6DXmtr2]== 0))
	{
		*preset = true; //enabling the auto control
	}
	else if((vexRT[Btn8UXmtr2]== 0) && (vexRT[Btn8DXmtr2]== 0) && (vexRT[Btn8LXmtr2]== 0)&& (vexRT[Btn8RXmtr2] == 0)
		&& (vexRT[Btn5UXmtr2] == 0) && (vexRT[Btn5DXmtr2]== 0) || (vexRT[Btn6UXmtr2]== 1) || (vexRT[Btn6DXmtr2]== 1))
	{
		*preset = false;	//enabling manual control
	}

	if(preset == true)
	{
		int target = 0;

		if((button8U == 0) && (button8D == 1) && (button8R == 0) && (button8L == 0)
			&& (button5U == 0) && (button5D == 0))
		{
			target = LOW_GOAL;
		}
		else if((button8U == 0) && (button8D == 0) && (button8R == 1) && (button8L == 0)
			&& (button5U == 0) && (button5D == 0))
		{
			target = MID_GOAL;
		}
		else if((button8U == 0) && (button8D == 1) && (button8R == 0) && (button8L == 0)
			&& (button5U == 0) && (button5D == 0))
		{
			target = HIGH_GOAL;
		}
		else if((button8U == 0) && (button8D == 0) && (button8R == 0) && (button8L == 0)
			&& (button5U == 0) && (button5D == 1))
		{
			target = GROUND;
		}
		else if((button8U == 0) && (button8D == 0) && (button8R == 0) && (button8L == 0)
			&& (button5U == 1) && (button5D == 0))
		{
			target = MAX_HEIGHT;
		}
		else if((button8U == 0) && (button8D == 0) && (button8R == 0) && (button8L == 1)
			&& (button5U == 0) && (button5D == 0))
		{
			target = SKYRISE_DISPENSER;
		}
		moveLift(target);
	}

	//manual control for lift
	else if(preset == false)
	{
		if((vexRT[Btn6UXmtr2] == 1) && (vexRT[Btn6DXmtr2] == 0))
		{
			lift(127);
		}
		else if((vexRT[Btn6DXmtr2] == 1) && (vexRT[Btn6UXmtr2] == 0))
		{
			lift(-127);
		}
		else
		{
			lift(0);
		}
	}
}

task usercontrol()
{

	bool preset = false; //initially preset is false 7to allow for manual control

	while(true)
	{
		presets(&preset);
	}

	//SensorType[in8] = sensorNone;
	//wait1Msec(1000);
	////Reconfigure Analog Port 8 as a Gyro sensor and allow time for ROBOTC to calibrate it
	//SensorType[in8] = sensorGyro;
	//wait1Msec(2000);
	int X2 = 0, Y1 = 0, X1 = 0, threshold = 15;

	//Create "deadzone" for Y1/Ch3
	if(abs(vexRT[Ch3]) > threshold)
		Y1 = vexRT[Ch3];
	else
		Y1 = 0;
	//Create "deadzone" for X1/Ch4
	if(abs(vexRT[Ch4]) > threshold)
		X1 = vexRT[Ch4];
	else
		X1 = 0;
	//Create "deadzone" for X2/Ch1
	if(abs(vexRT[Ch1]) > threshold)
		X2 = vexRT[Ch1];
	else
		X2 = 0;

	//Remote Control Commands
	motor[DFR] = Y1 - X2 - X1;
	motor[DBR] =  Y1 - X2 + X1;
	motor[DFL] = Y1 + X2 + X1;
	motor[DBL] =  Y1 + X2 - X1;
}


//touch2 refers to a lift limit
//touch1 refers to the back of the robot's touch sensor
