#pragma config(Motor,  port1,           rLift1,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port2,           DFR,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           rLift2,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           rLift3,        tmotorVex393, openLoop)
#pragma config(Motor,  port5,           lLift1,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           lLift2,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           DBL,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           DBR,           tmotorVex393, openLoop)
#pragma config(Motor,  port9,           DFL,           tmotorVex393, openLoop)
#pragma config(Motor,  port10,          lLift3,        tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int valveUseCount = 0;
float valveUseMultiplier = 0.2;
long valveOpenTime = 50; //

long timeValveOff = 0;
bool pneumaticButtonDown = false;

task main()
{
	while(true)
	{
		motor[DFR] = vexRT[Ch2];
		motor[DBR] = vexRT[Ch2];
		motor[DFL] = vexRT[Ch3];
		motor[DBL] = vexRT[Ch3];
	}
}

//function for right lift
void rightLift(int a)//3 and 5 reverse!!!
{
	motor[rLift1] = a;
	motor[rLift2] = a;
	motor[rLift3] = a;
}
//function for left lift
void leftLift (int a)
{
	motor[lLift1] = a;
	motor[lLift2] = a;
	motor[lLift3] = a;
}
//function for lift
void lift(int a)
{
	rightLift(a);
	leftLift(a);
}


task main()//lift control
{
	while(true)
	{
		if ((vexRT[Btn6U]==1)&&(vexRT[Btn6D]==0))
		{
			lift(50);
		}
		else if ((vexRT[Btn6D]==1)&&(vexRT[Btn6U]==0))
		{
			lift(-50);
		}
		else
		{
			lift(0);
		}
	}
}

task main()
{
	while(1 == 1)
	{
		//get current time
		long currentTime = nSysTime;
		if(currentTime > timeValveOff)
		{
			SensorValue[solenoid] = 0;
		}
		if((vexRT[Btn5U] == 1) && !pneumaticButtonDown)           // If button 6U (upper right shoulder button) is pressed:
		{
			pneumaticButtonDown = true;
			SensorValue[solenoid] = 1;
			timeValveOff = nSysTime + valveOpenTime;
			timeValveOff += (long)(valveUseMultiplier * valveUseCount * 50);
			valveUseCount++;
		}
		if((vexRT[Btn5U] == 0) && pneumaticButtonDown)
		{
			pneumaticButtonDown = false;
		}
	}
}
