#pragma config(Sensor, dgtl1,  limit1,         sensorTouch)
#pragma config(Sensor, dgtl2,  limit2,         sensorTouch)
#pragma config(Sensor, dgtl7,  solenoid,       sensorDigitalOut)
#pragma config(Motor,  port1,           DFR,           tmotorVex393, openLoop)
#pragma config(Motor,  port2,           DBR,           tmotorVex393, openLoop)
#pragma config(Motor,  port3,           DFL,           tmotorVex393, openLoop)
#pragma config(Motor,  port4,           DBL,           tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int MIN_JOYSTICK_ACTIVATION_THRESHOLD = 10;//tank drive threshold
const int error = 10;//define the error

int valveUseCount = 0;
float valveUseMultiplier = 0.2;
long valveOpenTime = 50; //

long timeValveOff = 0;
bool pneumaticButtonDown = false;

void gyroTurn(int degrees10)//specify the amount of degrees to turn
{
	while((abs(SensorValue[in8]) < degrees10 + error) || (abs(SensorValue[in8]) < degrees10 - error))
	{
		motor[port1] = 63;
		motor[port2] = -63;
	}

	motor[port1] = -5;//brake/return to original
	motor[port2] = 5;
	wait1Msec(250);
}

void drive_straight(float dist, int speed)
{
	while((SensorValue(dgtl1) < 360 * dist / (4 * PI) + error) || (SensorValue(dgtl1) < 360 * dist / (4 * PI) + error))
		motor[port1] = speed;

}

task autonomous()
{
	SensorType[in8] = sensorNone;
	wait1Msec(1000);
	//Reconfigure Analog Port 8 as a Gyro sensor and allow time for ROBOTC to calibrate it
	SensorType[in8] = sensorGyro;
	wait1Msec(2000);

	if(SensorValue(limit1) == 0) //hang a cube from the back, move backwards until the limit switch is pressed
	{
		motor[port1] = -100;
		motor[port2] = -100;
	}
	else if(SensorValue(limit1) == 1)
	{
		wait1Msec(1000); //wait for the cube to release from the robot
		motor[port1] = 100;
		motor[port2] = 100;
	}

	gyroTurn(45);//turns 45 degrees

	drive_straight(sqrt(2), 50);//returns to starting position
	drive_straight(1.5, 50);
	//do something with intake
	if(SensorValue(limit1) == 0)
	{
		motor[port1] = -100;
		motor[port2] = -100;

	}
}

task main()
{
	while(1 == 1)
	{
		//get current time
		long currentTime = nSysTime;
		if(currentTime > timeValveOff)
		{
			SensorValue[solenoid] = 0;
		}
		if((vexRT[Btn5U] == 1) && !pneumaticButtonDown)           // If button 6U (upper right shoulder button) is pressed:
		{
			pneumaticButtonDown = true;
			SensorValue[solenoid] = 1;
			timeValveOff = nSysTime + valveOpenTime;
			timeValveOff += (long)(valveUseMultiplier * valveUseCount * 50);
			valveUseCount++;
		}
		if((vexRT[Btn5U] == 0) && pneumaticButtonDown)
		{
			pneumaticButtonDown = false;
		}
	}






	if(vexRT[Btn6D] == 1)
	{
		if(SensorValue(limit2) == 0)
		{
			//runliftdown
		}
		else
		{
			//do nothing
		}
	}
	else if(vexRT[Btn6U] == 1)
	{
		//runliftup
	}
	else
	{
		//donothing
	}

	//tank drive
	if(abs(vexRT[Ch3]) > MIN_JOYSTICK_ACTIVATION_THRESHOLD)
	{
		motor[DFL] = vexRT[Ch3];
		motor[DBL] = vexRT[Ch3];
	}
	else
	{
		motor[DFL] = 0;
		motor[DBL] = 0;
	}

	if(abs(vexRT[Ch2]) > MIN_JOYSTICK_ACTIVATION_THRESHOLD)
	{
		motor[DFR] = vexRT[Ch2];
		motor[DBR] = vexRT[Ch2];
	}
	else
	{
		motor[DFR] = 0;
		motor[DBR] = 0;
	}
}


//touch2 refers to a lift limit
//touch1 refers to the back of the robot's touch sensor
