#pragma config(Sensor, dgtl1,  touchSensorV2,  sensorTouch)
#pragma config(Sensor, dgtl2,  touchySensorV2, sensorTouch)
#pragma config(Sensor, dgtl5,  touchySensor,   sensorTouch)
#pragma config(Sensor, dgtl6,  touchSensor,    sensorTouch)
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           rightMotor,    tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/*----------------------------------------------------------------------------------------------------*\
|*63                                        - Wait for Push 1 -                                         *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs the robot to move forward at half speed until the bumper sensor is         *|
|*  pressed.  There is a two second pause at the beginning of the program.                            *|
?
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" mode, but may not be needed for all robot configurations.                       *|
|*
*|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor Port 2        rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor Port 3        leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Digital Port 6      touchSensor         VEX Bumper Switch     Front mounted, facing forward.    *|
\*-----------------------------------------------------------------------------------------------4246-*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	while(true)
	{
		int bumperState;

		if((SensorValue(touchSensor) == 1) || (SensorValue(touchSensorV2) == 1))
		{
			bumperState = 1;
		}


		if((SensorValue(touchySensor) == 1) || (SensorValue(touchySensorV2) == 1))
		{
			bumperState = 0;
		}


		if(bumperState == 0)	 // Loop while robot's bumper/touch sensor isn't pressed in
		{
			motor[rightMotor] = vexRT[Ch2];
			motor[leftMotor] = vexRT[Ch3];	          // Motor on port3 is run at half (63) power forward
		}


	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
