#pragma config(Sensor, dgtl1,  bumper1,        sensorTouch)
#pragma config(Sensor, dgtl2,  bumper2,        sensorTouch)
#pragma config(Sensor, dgtl3,  bumper3,        sensorTouch)
#pragma config(Sensor, dgtl4,  bumper4,        sensorTouch)
#pragma config(Sensor, dgtl5,  bumper5,        sensorTouch)
#pragma config(Motor,  port2,           DFR,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           DBR,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           DFL,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           DBL,           tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void driveRight(int a)
{
	motor[DFR]=a;
	motor[DBR]=a;
}

void driveLeft(int a)
{
	motor[DFL]=a;
	motor[DBL]=a;
}

void turnRight(int a)
{
	driveRight(-a);
	driveLeft(a);
}

task usercontrol()
{
	motor[DFR]=vexRT[Ch3];
	motor[DBR]=vexRT[Ch3];
	motor[DFL]=vexRT[Ch2];
	motor[DBL]=vexRT[Ch2];
}

task main()
{
	while(true)
	{
		if((SensorValue[bumper1]==1)||(SensorValue[bumper2]==1)||(SensorValue[bumper3]==1)||(SensorValue[bumper4]==1)||(SensorValue[bumper5]==1))
		{
			driveRight(0);
			driveLeft(0);
			wait1Msec(5000);
		}
		else
		{
			driveRight(127);
			driveLeft(127);
		}
	}
}
