#pragma config(Motor,  port2,           onetwo,        tmotorVex393, openLoop)
#pragma config(Motor,  port3,           sevensix,      tmotorVex393, openLoop)
#pragma config(Motor,  port4,           elevensix,     tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int THRESH = 32;

int magCalc(float inputo, float inputt)
{
	return sqrt(pow(inputo, 2.0) + pow(inputt, 2.0));
}

void omniControl(float joyY, float joyX, float joyROT)
{
	motor[onetwo] = -joyX * 0.75 + joyROT * 0.25;
	motor[sevensix] = joyX*1.5 + joyY * -sqrt(3.0)*1.5 + joyROT * 0.25;
	motor[elevensix] = joyX*1.5 + joyY * sqrt(3.0) * 1.5 + joyROT * 0.25;
}

task main()
{
	while(true)
	{
		omniControl(vexRT[Ch3], vexRT[Ch4], vexRT[Ch1]);
	}
}
